version: '3.8'

services:
  menu-digital:
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: menu-digital-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_BUSINESS_NAME=Menu Digital
      - NEXT_PUBLIC_WHATSAPP_NUMBER=5511999999999
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 30s
    networks:
      - menu-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.menu-digital.rule=Host(`localhost`)"
      - "traefik.http.routers.menu-digital.entrypoints=web"

networks:
  menu-network:
    driver: bridge
    name: menu-digital-network

# Para desenvolvimento, use o docker-compose.dev.yml
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
